
# Tomcat
server:
  port: 8081


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vhr?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true