package com.common.sftp;

import java.util.Date;

public class SftpFileParameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.TRAN_ID
     *
     * @mbggenerated
     */
    private String tranId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.HOST
     *
     * @mbggenerated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.PORT
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.USER_PASSWORD
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.FTP_DIR
     *
     * @mbggenerated
     */
    private String ftpDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.LOCAL_DIR
     *
     * @mbggenerated
     */
    private String localDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.IS_MKDIR
     *
     * @mbggenerated
     */
    private String isMkdir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.IS_VALID
     *
     * @mbggenerated
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.IS_CRYPT
     *
     * @mbggenerated
     */
    private String isCrypt;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sftp_file_parameter.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.ID
     *
     * @return the value of sftp_file_parameter.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.ID
     *
     * @param id the value for sftp_file_parameter.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.TRAN_ID
     *
     * @return the value of sftp_file_parameter.TRAN_ID
     *
     * @mbggenerated
     */
    public String getTranId() {
        return tranId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.TRAN_ID
     *
     * @param tranId the value for sftp_file_parameter.TRAN_ID
     *
     * @mbggenerated
     */
    public void setTranId(String tranId) {
        this.tranId = tranId == null ? null : tranId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.HOST
     *
     * @return the value of sftp_file_parameter.HOST
     *
     * @mbggenerated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.HOST
     *
     * @param host the value for sftp_file_parameter.HOST
     *
     * @mbggenerated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.PORT
     *
     * @return the value of sftp_file_parameter.PORT
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.PORT
     *
     * @param port the value for sftp_file_parameter.PORT
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.USER_NAME
     *
     * @return the value of sftp_file_parameter.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.USER_NAME
     *
     * @param userName the value for sftp_file_parameter.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.USER_PASSWORD
     *
     * @return the value of sftp_file_parameter.USER_PASSWORD
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.USER_PASSWORD
     *
     * @param userPassword the value for sftp_file_parameter.USER_PASSWORD
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.FTP_DIR
     *
     * @return the value of sftp_file_parameter.FTP_DIR
     *
     * @mbggenerated
     */
    public String getFtpDir() {
        return ftpDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.FTP_DIR
     *
     * @param ftpDir the value for sftp_file_parameter.FTP_DIR
     *
     * @mbggenerated
     */
    public void setFtpDir(String ftpDir) {
        this.ftpDir = ftpDir == null ? null : ftpDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.LOCAL_DIR
     *
     * @return the value of sftp_file_parameter.LOCAL_DIR
     *
     * @mbggenerated
     */
    public String getLocalDir() {
        return localDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.LOCAL_DIR
     *
     * @param localDir the value for sftp_file_parameter.LOCAL_DIR
     *
     * @mbggenerated
     */
    public void setLocalDir(String localDir) {
        this.localDir = localDir == null ? null : localDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.IS_MKDIR
     *
     * @return the value of sftp_file_parameter.IS_MKDIR
     *
     * @mbggenerated
     */
    public String getIsMkdir() {
        return isMkdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.IS_MKDIR
     *
     * @param isMkdir the value for sftp_file_parameter.IS_MKDIR
     *
     * @mbggenerated
     */
    public void setIsMkdir(String isMkdir) {
        this.isMkdir = isMkdir == null ? null : isMkdir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.IS_VALID
     *
     * @return the value of sftp_file_parameter.IS_VALID
     *
     * @mbggenerated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.IS_VALID
     *
     * @param isValid the value for sftp_file_parameter.IS_VALID
     *
     * @mbggenerated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sftp_file_parameter.CREATE_DATE
     *
     * @return the value of sftp_file_parameter.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sftp_file_parameter.CREATE_DATE
     *
     * @param createDate the value for sftp_file_parameter.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getIsCrypt() {
        return isCrypt;
    }

    public void setIsCrypt(String isCrypt) {
        this.isCrypt = isCrypt;
    }
}